### ISSUE TITLE
Unable to place normal blocks after limit reached

### ISSUE THREAD

**Issue by Rongmario** [MJRLegends/TileEntityLimiter#3]
https://github.com/MJRLegends/TileEntityLimiter/blob/master/src/main/java/com/mjr/tileentitylimiter/MainEventHandler.java

Your PlaceEvent does not check if blockSnapshot#getCurrentBlock() has TE or not

**Comment by MJRLegends** [comment]
Yeah it checks the tile map for the chunk and world which would only contain tile entities. So yeah it checks on every block even normal blocks but they dont get counted but the check wont cause any issues or tick time

**Comment by BlueAgent** [comment]
To be more clear, even if the block you're going to place doesn't have a tile entity, it still prevents the block from being placed once the limit is reached (e.g. Stone).

**Comment by MJRLegends** [comment]
Fair enough will fix, the @Rongmario wasnt clear with the actual issue

**Comment by MJRLegends** [comment]
Updates have been released
