### ISSUE TITLE
Add blacklist/whitelist for TileEntities that can/cannot be placed when limit is up

### ISSUE THREAD

**Issue by Rongmario** [MJRLegends/TileEntityLimiter#4]
Things like conduits and pipes must exceed the limit easily, or another purpose is to allow non-ticking TEs to be allowed through a whitelist etc.

**Comment by MJRLegends** [comment]
Maybe

**Comment by BlueAgent** [comment]
IMO a black/whitelist feature is crucial for your mod.
As it stands I can't see it being very useful at all, unless the pack forgoes wiring that has tile entities for each block (like a magic only pack, or limited to XNet and AA lasers).

**Comment by MJRLegends** [comment]
Its more aimed at servers this mod, and even wires are tickable to server would want them to be limited to. But for you two i will add a blacklist.

**Comment by MJRLegends** [comment]
Updates have been released
