### ISSUE TITLE
Mod is not loading and code is broken in multiple places

### ISSUE THREAD

**Issue by Mysticpasta1** [MJRLegends/TileEntityLimiter#6]
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes

### Description of Issue
Mod is broken really bad, SubscribeEvent doesn't work due to no Mod.EventHandler above it, the config will never be created, and nothing is loading correctly

### Steps to Reproduce Issue
1. Try to load the mod in 1.12.2 forge latest 
2. It doesn't load anything, no config, nothing

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> No Crash Log because it doesn't load at all!

**Screenshots (if applicable):** 

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** TileEntityLimiter-1.12.2-1.0.3.jar
**Where did this bug happen:** Both

### Additional Information
I will maintain and fix it for you if you have abandoned it

**Comment by MJRLegends** [comment]
Hey sorry for the huge delay in getting back to you, but yea it wont work for Client instances, its a server side only mod for dedicated servers
